---
opsman_ip: "{{ tanzu_opsman_bosh.opsman_ip }}"
opsman_username: "{{ tanzu_opsman_bosh.opsman_username }}"
opsman_password: "{{ tanzu_opsman_bosh.opsman_password }}"

bosh_networks: "{{ tanzu_opsman_bosh.bosh_networks }}"
bosh_ntp: "{{ tanzu_opsman_bosh.ntp }}"

bosh_vcenter_url: "{{ tanzu_opsman_bosh.vcenter_url }}"
bosh_vcenter_cluster: "{{ tanzu_opsman_bosh.vcenter_cluster }}"
bosh_vcenter_datacenter: "{{ tanzu_opsman_bosh.vcenter_datacenter }}"
bosh_vcenter_datastore_ephemeral: "{{ tanzu_opsman_bosh.vcenter_datastore }}"
bosh_vcenter_datastore_persistent: "{{ tanzu_opsman_bosh.vcenter_datastore }}"
bosh_vcenter_username: "{{ tanzu_opsman_bosh.vcenter_username }}"
bosh_vcenter_password: "{{ tanzu_opsman_bosh.vcenter_password }}"

bosh_nsx_url: "{{ tanzu_opsman_bosh.nsx_url | default(omit) }}"
bosh_nsx_username: "{{ tanzu_opsman_bosh.nsx_username | default(omit) }}"
bosh_nsx_password: "{{ tanzu_opsman_bosh.nsx_password | default(omit) }}"
bosh_nsx_use_policy_api: "{{ tanzu_opsman_bosh.nsx_use_policy_api | default(false) }}"
bosh_template_file: "{{ tanzu_opsman_bosh.bosh_template_file }}"

bosh_ssh_public_key: "{{ tanzu_opsman_bosh.ssh_public_key }}"
bosh_username: "{{ tanzu_opsman_bosh.username }}"
bosh_password: "{{ tanzu_opsman_bosh.password }}"

bosh_trusted_ca_certs: "{{ tanzu_opsman_bosh.trusted_ca_certs | default('') }}"

bosh_disk_path: pcf_disk
bosh_template_folder: pcf_templates
bosh_vm_folder: pcf_vms
